version: "3"
services:
  flyway:
    image: boxfuse/flyway:5.2.4
    command: migrate
    volumes:
      - ../flyway:/flyway/conf
      - ../flyway/database/migrations:/flyway/sql
    depends_on:
      - db
  app:
      build: .
      volumes:
        - ./src:/app/src
      working_dir: /app
      depends_on:
        - db
      environment:
        NODE_ENV: development
      ports:
        - 5000:5000
      command: npm run start:debug
      restart: always
  db:
    image: postgres
    environment:
      POSTGRES_DB: nd
      POSTGRES_PASSWORD: 123123
    ports:
      - "5433:5432"
    restart: always